name: Build for K8s

on:
  # always run on branches which contain k8s
  push:
    branches:
      - '**k8s**'
  # in all other cases, build is triggered by successful tests
  workflow_call:

jobs:
  build:
    name: K8s Build
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ...
        run: |
          git branch
          git log --pretty=format:"%h - %an, %ar : %s"

  tfc:
    name: TFC
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TFC Apply
        run: |
          sleep 1
