name: Tests

on:
  push:

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tests ...
        run: |
          #sleep 10
          #exit $(( RANDOM % 2))
          echo '${{ github.ref }}'
          exit 1

  k8s:
    needs: [tests]
    uses: ./.github/workflows/k8s.yaml
    secrets: inherit
    if: |
      # asdfasdf
      (
        !cancelled() &&
        startsWith(github.ref, 'refs/heads/') &&
        contains(github.ref, 'k8s')
      )
      ||
      (success() && (
        github.ref == 'refs/heads/develop' ||
        github.ref == 'refs/heads/production' ||
        github.ref == 'refs/heads/main' ||
        startsWith(github.ref, 'refs/tags/')
      ))
