name: Tests

on: [push]

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tests ...
        run: |
          sleep 30

  k8s:
    needs: [tests]
    uses: ./.github/workflows/k8s.yaml
    secrets: inherit
    if: ${{ contains('k8s', github.ref) }}
