name: Tests

on: [push]

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Tests ...
        run: |
          sleep 30

