name: Tests

on:
  push:

jobs:
  u2004:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo -n iptables-save

  u2204:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo -n iptables-save

  u2404:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo -n iptables-save
